[build-system]
# Must be kept in sync with `setup_requirements` in `setup.py`
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "cffi>=1.4.1; python_implementation != 'PyPy'",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py36"]

[tool.mypy]
show_error_codes = true
check_untyped_defs = true
no_implicit_reexport = true

files = ["src/nacl"]

[[tool.mypy.overrides]]
module = [
    "nacl._sodium",
]
ignore_missing_imports = true